"use client"

import jsPDF from "jspdf"

import {
  Download,
} from "lucide-react"

type Props = {
  productivity: number
  completedTasks: number
  streak: number
  focusSessions: number
}

export default function ExportReportButton({
  productivity,
  completedTasks,
  streak,
  focusSessions,
}: Props) {

  function exportPDF() {

    const doc =
      new jsPDF()

    /* BACKGROUND */

    doc.setFillColor(
      248,
      250,
      252
    )

    doc.rect(
      0,
      0,
      210,
      297,
      "F"
    )

    /* HEADER */

    doc.setFont(
      "helvetica",
      "bold"
    )

    doc.setFontSize(28)

    doc.setTextColor(
      79,
      70,
      229
    )

    doc.text(
      "GoTaskly AI Report",
      20,
      30
    )

    /* SUBTITLE */

    doc.setFontSize(12)

    doc.setTextColor(
      100,
      116,
      139
    )

    doc.text(
      "AI-powered productivity intelligence and analytics summary.",
      20,
      40
    )

    /* DIVIDER */

    doc.setDrawColor(
      226,
      232,
      240
    )

    doc.line(
      20,
      50,
      190,
      50
    )

    /* SECTION TITLE */

    doc.setFontSize(18)

    doc.setTextColor(
      15,
      23,
      42
    )

    doc.text(
      "Performance Overview",
      20,
      70
    )

    /* STATS */

    const stats = [

      {
        label:
          "Productivity Score",

        value:
          `${productivity}%`,
      },

      {
        label:
          "Completed Tasks",

        value:
          `${completedTasks}`,
      },

      {
        label:
          "Best Streak",

        value:
          `${streak} Days`,
      },

      {
        label:
          "Focus Sessions",

        value:
          `${focusSessions}`,
      },
    ]

    let y = 90

    stats.forEach(
      (stat) => {

        doc.setFillColor(
          255,
          255,
          255
        )

        doc.roundedRect(
          20,
          y,
          170,
          20,
          6,
          6,
          "F"
        )

        doc.setFontSize(13)

        doc.setTextColor(
          71,
          85,
          105
        )

        doc.text(
          stat.label,
          28,
          y + 12
        )

        doc.setFont(
          "helvetica",
          "bold"
        )

        doc.setTextColor(
          79,
          70,
          229
        )

        doc.text(
          stat.value,
          165,
          y + 12
        )

        y += 30
      }
    )

    /* AI ANALYSIS */

    doc.setFontSize(18)

    doc.setTextColor(
      15,
      23,
      42
    )

    doc.text(
      "AI Analysis",
      20,
      220
    )

    doc.setFontSize(12)

    doc.setTextColor(
      71,
      85,
      105
    )

    const analysis =
      `
Your productivity momentum is improving steadily.

AI detected strong workflow consistency and positive habit adherence.

Recommended improvements:
• Increase deep work sessions
• Reduce task switching
• Maintain streak consistency
• Continue planner optimization
    `

    doc.text(
      analysis,
      20,
      235
    )

    /* FOOTER */

    doc.setFontSize(10)

    doc.setTextColor(
      148,
      163,
      184
    )

    doc.text(
      "Generated by GoTaskly AI Productivity Platform",
      20,
      285
    )

    /* SAVE */

    doc.save(
      "gotaskly-ai-report.pdf"
    )
  }

  return (

    <button

      onClick={exportPDF}

      className="
        inline-flex
        items-center
        gap-3

        rounded-2xl

        bg-gradient-to-r
        from-[#4f46e5]
        to-[#7c3aed]

        px-6
        py-4

        text-white
        font-semibold

        shadow-xl

        transition-all

        hover:scale-105
      "
    >

      <Download size={20} />

      Export AI Report

    </button>

  )
}